project_id = "btwmbpouybpcgygdymnw"

[functions.match-costumes]
verify_jwt = false

[functions.enhance-costumes]
verify_jwt = false

[functions.generate-guide]
verify_jwt = false

[functions.generate-hybrid]
verify_jwt = false